### ISSUE TITLE
Response 'Host name may not be empty' from function createPayment

### ISSUE THREAD

**Issue by marcelvanlangen** [blackbucksoftware/mollie-cfml#1]
I have followed the example in the docs.  I have an API key, but when I use the code, I get a struct back with an error message: 'Host name may not be empty'. Please advice on how to proceed!

**Comment by faxi05** [comment]
Could you share the code (without the actual key of course) you use to initialize the library?

**Comment by faxi05** [comment]
While fixing the sample for the other issue you reported it dawned on me what the cause for the host name error might be: You can leave out the baseUrl param during initialization altogether, it's optional.

**Comment by marcelvanlangen** [comment]
First of all, thanks for the superquick reply! I do not currently use the baseUrl, so that should not be the problem. My code is as follows:

`<cfset mollie = new model.mollie.mollie(
		key = application.setting.mollieApiSleutel,
		baseUrl = ''
	)>`

`<cfset paymentLink = mollie.createPayment(
        currency = "EUR",
        value = "25.00",
        description = "Aanschaf templateset",
        redirectUrl = "https://demo.normity.local/",
        webhookUrl = "https://my.site.com/mollie",
        method = ["sofort","giropay","creditcard","applepay","ideal"],
        metadata = [ { "orderid": "NORM-001" } ]
    )>
	<cfdump var="#paymentLink#">`

When I dump the variable 'paymentLink' I get a struct with 3 items:
- data (empty string)
- error (containing the string 'Host name may not be empty')
- success (containing the boolean false)

Hope this helps!

**Comment by marcelvanlangen** [comment]
BTW I do know that the redirectURL and webhookURL are currently not available online, but the same message appears when I remove the webhoopURL and change the redirectUrl to a valid URL online.

**Comment by faxi05** [comment]
Looks like our code example is to blame for this one :)

It should work if you change your initialization code like this:

`<cfset mollie = new model.mollie.mollie( key = application.setting.mollieApiSleutel ) />`

Let me know if that helps.

**Comment by marcelvanlangen** [comment]
Awesome, that is the solution. Succes = true! Thank you very much for the quick and solid answers.

**Comment by faxi05** [comment]
Awesome! Glad I could help.
