### ISSUE TITLE
Small error in example for createPayment

### ISSUE THREAD

**Issue by marcelvanlangen** [blackbucksoftware/mollie-cfml#2]
In the example for creating the payment, the field method has the value:

_method = "sofort,giropay,creditcard,applepay,ideal,eps"_

This should be an array and thus:

_method = ["sofort","giropay","creditcard","applepay","ideal","eps"]_

**Comment by faxi05** [comment]
Hi Marcel,

good catch. We'll fix the example.

-- Lutz
